//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookHouse.Clients.Magfa.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MagfaStatus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MagfaStatus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookHouse.Clients.Magfa.Resources.MagfaStatus", typeof(MagfaStatus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست با موفقیت اجرا شد.
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره گيرنده نادرست است.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول آرايه پارامتر messageBodies با طول آرايه گيرندگان تطابق ندارد.
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول آرايه پارامتر messageClass با طول آرايه گيرندگان تطابق ندارد.
        /// </summary>
        internal static string _102 {
            get {
                return ResourceManager.GetString("102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول آرايه پارامتر senderNumbers با طول آرايه گيرندگان تطابق ندارد.
        /// </summary>
        internal static string _103 {
            get {
                return ResourceManager.GetString("103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول آرايه پارامتر udhs با طول آرايه گيرندگان تطابق ندارد.
        /// </summary>
        internal static string _104 {
            get {
                return ResourceManager.GetString("104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول آرايه پارامتر priorities با طول آرايه گيرندگان تطابق ندارد.
        /// </summary>
        internal static string _105 {
            get {
                return ResourceManager.GetString("105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آرايه‌ی گيرندگان خالی است.
        /// </summary>
        internal static string _106 {
            get {
                return ResourceManager.GetString("106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول آرايه پارامتر گيرندگان بيشتر از طول مجاز است.
        /// </summary>
        internal static string _107 {
            get {
                return ResourceManager.GetString("107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آرايه‌ی فرستندگان خالی است.
        /// </summary>
        internal static string _108 {
            get {
                return ResourceManager.GetString("108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول آرايه پارامتر encoding با طول آرايه گيرندگان تطابق ندارد.
        /// </summary>
        internal static string _109 {
            get {
                return ResourceManager.GetString("109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول آرايه پارامتر checkingMessageIds با طول آرايه گيرندگان تطابق ندارد.
        /// </summary>
        internal static string _110 {
            get {
                return ResourceManager.GetString("110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتويات پيامک (تركيب UDH و متن) خالی است. (بررسی دوباره‌ی متن پيامک و پارامتر UDH).
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مانده اعتبار ريالی مورد نياز برای ارسال پیامک کافی نيست.
        /// </summary>
        internal static string _14 {
            get {
                return ResourceManager.GetString("14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرور در هنگام ارسال پيام مشغول برطرف نمودن ايراد داخلی بوده است. (ارسال مجدد درخواست).
        /// </summary>
        internal static string _15 {
            get {
                return ResourceManager.GetString("15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب غيرفعال است. (تماس با واحد فروش سيستم‌های ارتباطی).
        /// </summary>
        internal static string _16 {
            get {
                return ResourceManager.GetString("16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب منقضی شده است. (تماس با واحد فروش سيستم‌های ارتباطی).
        /// </summary>
        internal static string _17 {
            get {
                return ResourceManager.GetString("17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام كاربری و يا كلمه عبور نامعتبر است. (بررسی مجدد نام كاربری و كلمه عبور).
        /// </summary>
        internal static string _18 {
            get {
                return ResourceManager.GetString("18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست معتبر نيست. (تركيب نام كاربری، رمز عبور و دامنه اشتباه است. تماس با واحد فروش برای دريافت كلمه عبور جديد).
        /// </summary>
        internal static string _19 {
            get {
                return ResourceManager.GetString("19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره فرستنده نادرست است.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره فرستنده به حساب تعلق ندارد.
        /// </summary>
        internal static string _20 {
            get {
                return ResourceManager.GetString("20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اين سرويس برای حساب فعال نشده استc.
        /// </summary>
        internal static string _22 {
            get {
                return ResourceManager.GetString("22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر امکان پردازش درخواست جديد وجود ندارد، لطفا دوباره سعی كنيد. (ارسال مجدد درخواست).
        /// </summary>
        internal static string _23 {
            get {
                return ResourceManager.GetString("23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه پيامک معتبر نيست. (ممكن است شناسه پيامک اشتباه و يا متعلق به پيامكی باشد كه بيش از يک روز از ارسال آن گذشته).
        /// </summary>
        internal static string _24 {
            get {
                return ResourceManager.GetString("24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام متد درخواستی معتبر نيست. (بررسی نگارش نام متد با توجه به بخش متدها در اين راهنما).
        /// </summary>
        internal static string _25 {
            get {
                return ResourceManager.GetString("25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره گيرنده در ليست سياه اپراتور قرار دارد. (ارسال پيامک‌های تبليغاتی برای اين شماره امكان‌پذير نيست).
        /// </summary>
        internal static string _27 {
            get {
                return ResourceManager.GetString("27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره گیرنده، بر اساس پیش‌شماره در حال حاضر در مگفا مسدود است.
        /// </summary>
        internal static string _28 {
            get {
                return ResourceManager.GetString("28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس IP مبدا، اجازه دسترسی به این سرویس را ندارد.
        /// </summary>
        internal static string _29 {
            get {
                return ResourceManager.GetString("29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامتر encoding نامعتبراست. (بررسی صحت و هم‌خوانی متن پيامک با encoding انتخابی).
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد بخش‌های پیامک بیش از حد مجاز استاندارد (۲۶۵ عدد) است.
        /// </summary>
        internal static string _30 {
            get {
                return ResourceManager.GetString("30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامتر mclass نامعتبر است.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامتر UDH نامعتبر است.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
    }
}
